services:
  postgres-db:
    image: postgres:16.6-alpine
    container_name: production_postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - '5437:5432'
    environment:
      POSTGRES_DB: ${SPRING_DATASOURCE_NAME:-savemymoney}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-secretpassword}
    networks:
      - app-network
  spring-app:
    image: docker.io/altamirobruno/save-my-money:latest
    container_name: spring_boot_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      # Injecting environment variables into Spring Boot
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/${SPING_DATASOURCE_URL:-savemymoney}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-secretpassword}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres-db
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: production_pgadmin
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres-db
    networks:
      - app-network

volumes:
  postgres_data:
  pgadmin-data:

networks:
  app-network:
    driver: bridge

