spring.application.name=save-my-money
spring.datasource.url=jdbc:postgresql://localhost:5435/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.public.key=classpath:public.pem
jwt.private.key=classpath:private.pem