spring.application.name=save-my-money
#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/savemymoney}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-long-shape-at4ka8mi-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_uKdIl2gbT5Rk}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.public.key=classpath:public.pem
jwt.private.key=classpath:private.pem
logging.level.org.springframework.security=DEBUG